import type { Tool } from "../types";

export const tools: Tool[] = [
    // --- Text Cleaning ---
    {
        id: "line-break-remover",
        name: "Line Break Remover",
        category: "Text Cleaning",
        apiStep: "line-break-remover",
        description: "Remove line breaks and extra spaces from pasted text",
        placeholder: "Paste text with\\nline breaks\\nand extra spaces here...",
    },
    {
        id: "remove-all-spaces",
        name: "Remove All Spaces",
        category: "Text Cleaning",
        apiStep: "remove-all-spaces",
        description: "Remove all spaces or whitespace from text",
        placeholder: "Text with spaces to remove...",
    },
    {
        id: "sort-remove-duplicates",
        name: "Sort & Deduplicate",
        category: "Text Cleaning",
        apiStep: "sort-remove-duplicates",
        description: "Sort lists alphabetically and remove duplicate lines",
        placeholder: "apple\\nbanana\\napple\\ncherry",
    },
    {
        id: "accent-remover",
        name: "Accent Remover",
        category: "Text Cleaning",
        apiStep: "accent-remover",
        description: "Remove accents and diacritics, convert to plain ASCII",
        placeholder: "Crème brûlée -> Creme brulee",
    },
    {
        id: "title-case-converter",
        name: "Title Case Converter",
        category: "Text Cleaning",
        apiStep: "title-case-converter",
        description: "Convert text to title case, uppercase, lowercase, or camelCase",
        placeholder: "convert my text to title case",
    },
    {
        id: "word-counter",
        name: "Word Counter",
        category: "Text Cleaning",
        apiStep: "word-counter",
        description: "Count words, characters, sentences, paragraphs",
        placeholder: "Paste text to count...",
    },
    {
        id: "rosetta-stone",
        name: "Rosetta Stone (Pro)",
        category: "Text Cleaning",
        apiStep: "rosetta-stone",
        description: "Normalize multilingual text, clean punctuation",
        placeholder: "Text with «quotes» and ¿punctuation?...",
    },
    {
        id: "email-extractor",
        name: "Email Extractor",
        category: "Text Cleaning",
        apiStep: "email-extractor",
        description: "Extract and validate email addresses from text",
        placeholder: "Contact us at support@example.com or sales@example.com...",
    },

    // --- Numbers & Formats ---
    {
        id: "phone-number-formatter",
        name: "Phone Number Formatter",
        category: "Numbers & Formats",
        apiStep: "phone-number-formatter",
        description: "Format phone numbers to E.164, international, or national styles",
        placeholder: "5551234567 -> (555) 123-4567",
    },
    {
        id: "number-to-words",
        name: "Number to Words",
        category: "Numbers & Formats",
        apiStep: "number-to-words",
        description: "Convert numbers to words for checks and documents",
        placeholder: "123.45 -> one hundred twenty-three and 45/100",
    },
    {
        id: "roman-numerals-converter",
        name: "Roman Numerals Converter",
        category: "Numbers & Formats",
        apiStep: "roman-numerals-converter",
        description: "Convert between numbers and Roman numerals",
        placeholder: "2024 -> MMXXIV",
    },
    {
        id: "sms-length-calculator",
        name: "SMS Length Calculator",
        category: "Numbers & Formats",
        apiStep: "sms-length-calculator",
        description: "Calculate SMS length, encoding, and segment counts",
        placeholder: "Type your SMS message here...",
    },
    {
        id: "unix-timestamp-converter",
        name: "Unix Timestamp Converter",
        category: "Numbers & Formats",
        apiStep: "unix-timestamp-converter",
        description: "Convert Unix timestamps to human-readable dates",
        placeholder: "1715000000",
    },

    // --- Developer Tools ---
    {
        id: "json-formatter",
        name: "JSON Formatter",
        category: "Developer Tools",
        apiStep: "json-formatter",
        description: "Format, beautify, minify, and validate JSON",
        placeholder: "{\"unformatted\": \"json\"}",
    },
    {
        id: "base64-encode-decode",
        name: "Base64 Encode/Decode",
        category: "Developer Tools",
        apiStep: "base64-encode-decode",
        description: "Convert text to and from Base64 encoding",
        placeholder: "Encode me to Base64...",
    },
    {
        id: "url-encode-decode",
        name: "URL Encode/Decode",
        category: "Developer Tools",
        apiStep: "url-encode-decode",
        description: "Encode and decode URLs and query strings",
        placeholder: "https://example.com/path?query=param",
    },
    {
        id: "sanitize-url",
        name: "Sanitize URLs",
        category: "Developer Tools",
        apiStep: "sanitize-url",
        description: "Remove tracking parameters (UTM, fbclid) from URLs",
        placeholder: "https://example.com?utm_source=tracking&id=123",
    },
    {
        id: "mime-type-lookup",
        name: "MIME Type Lookup",
        category: "Developer Tools",
        apiStep: "mime-type-lookup",
        description: "Look up MIME types and file extensions",
        placeholder: ".json or application/json",
    },
    {
        id: "jwt-decoder",
        name: "JWT Decoder",
        category: "Developer Tools",
        apiStep: "jwt-decoder",
        description: "Decode JWT tokens and inspect payload",
        placeholder: "eyJh...",
    },
    {
        id: "uuid-generator",
        name: "UUID Generator",
        category: "Developer Tools",
        apiStep: "uuid-generator",
        description: "Generate version 4 and version 7 UUIDs",
        placeholder: "Generates generic.input (ignored)",
    },
    {
        id: "cron-generator",
        name: "Cron Generator",
        category: "Developer Tools",
        apiStep: "cron-generator",
        description: "Generate cron expressions from natural language",
        placeholder: "every day at 5pm",
    },
    {
        id: "sql-formatter",
        name: "SQL Formatter",
        category: "Developer Tools",
        apiStep: "sql-formatter",
        description: "Format and beautify SQL queries",
        placeholder: "SELECT * FROM users WHERE id = 1",
    },
    {
        id: "regex-tester",
        name: "Regex Tester",
        category: "Developer Tools",
        apiStep: "regex-tester",
        description: "Test regular expressions",
        placeholder: "Test your regex pattern here...",
    },
    {
        id: "diff-checker",
        name: "Diff Checker",
        category: "Developer Tools",
        apiStep: "diff-checker",
        description: "Compare two text blocks (Simple usage)",
        placeholder: "Original\n---\nModified",
    },
    {
        id: "hex-converter",
        name: "Hex Converter",
        category: "Developer Tools",
        apiStep: "hex-converter",
        description: "Convert text/numbers to hexadecimal",
        placeholder: "Convert me to hex",
    },
    {
        id: "hash-generator",
        name: "Hash Generator",
        category: "Developer Tools",
        apiStep: "hash-generator",
        description: "Generate MD5, SHA-256 hashes",
        placeholder: "Text to hash...",
    },
    {
        id: "csv-json-converter",
        name: "CSV ↔ JSON",
        category: "Developer Tools",
        apiStep: "csv-json-converter",
        description: "Convert CSV to JSON and vice versa",
        placeholder: "id,name\\n1,Alice",
    },
    {
        id: "yaml-json-converter",
        name: "YAML ↔ JSON",
        category: "Developer Tools",
        apiStep: "yaml-json-converter",
        description: "Convert YAML to JSON and vice versa",
        placeholder: "key: value",
    },
    {
        id: "markdown-preview",
        name: "Markdown Preview",
        category: "Developer Tools",
        apiStep: "markdown-preview",
        description: "Preview Markdown as HTML",
        placeholder: "# Hello World\\n\\n**Bold text**",
    },
    {
        id: "token-analyzer",
        name: "Token Counter",
        category: "Developer Tools",
        apiStep: "token-analyzer",
        description: "Count tokens for LLMs",
        placeholder: "Paste text to count tokens...",
    },
    {
        id: "subnet-calculator",
        name: "Subnet Calculator",
        category: "Developer Tools",
        apiStep: "subnet-calculator",
        description: "Calculate CIDR subnets",
        placeholder: "192.168.1.0/24",
    }
];
